version: 2.1

executors:
  python:
    docker:
      - image: circleci/python

orbs:
  ansible: orbss/ansible-playbook@0.0.5

jobs:
  ansible-playbook:
    executor: python

    parameters:
      version:
        description: |
          Ansible version
        type: string
        default: ''

      playbook:
        description: |
          The path of Ansible playbook
        type: string

    steps:
      - checkout
      - add_ssh_keys:
              fingerprints:
                - 9a:f2:be:29:25:ac:ea:4c:19:76:b0:bc:bc:9b:e9:7b
      - ansible/install:
          version: <<parameters.version>>
      - ansible/playbook:
          playbook: <<parameters.playbook>>
      
workflows:
  version: 2
  test-checkout:
    jobs:
      - ansible-playbook:
          version: "2.15.4"
          playbook:  /ansible/playbooks/ec2_deploy.yml
          
