version: 2.1           

orbs:
  python: circleci/python@2.0.3
  ansible: orbss/ansible-playbook@0.0.5

parameters:
  run-development-terraform-build:
    type: boolean
    default: false
  run-modules-terraform-build:
    type: boolean
    default: false
  run-raisetech-sample-config:
    type: boolean
    default: false     

executors:
  terraform:
    docker:
      - image: hashicorp/terraform:1.5.7
  ansible:
    docker:
      - image: circleci/python

jobs:
  plan:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Plan
          command: |
            cd ./terraform/environments/development
            terraform init
            terraform plan 

  apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Terraform Apply
          command: |
            cd ./terraform/environments/development
            terraform init
            terraform apply -auto-approve 

  ansible-playbook:
    executor: ansible
    parameters:
      version:
        description: |
          Ansible version
        type: string
        default: ''

      playbook:
        description: |
          The path of Ansible playbook
        type: string
    steps:
      - checkout
      - add_ssh_keys:
              fingerprints:
                - 9a:f2:be:29:25:ac:ea:4c:19:76:b0:bc:bc:9b:e9:7b
      - ansible/install:
          version: <<parameters.version>>
      - ansible/playbook:
          playbook: <<parameters.playbook>>

  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

workflows:
  # when pipeline parameter, run-development-terraform-build is true, the
  # job is triggered.
  terraform-build-and-deploy:
    when: 
      or: [<< pipeline.parameters.run-development-terraform-build >>, << pipeline.parameters.run-modules-terraform-build >>]
    jobs:
      - plan          
      - apply:
          requires:
            - plan
      - ansible-playbook:
          version: "2.15.4"
          playbook:  /ansible/playbooks/ec2_deploy.yml
          requires:
            - apply

  # when pipeline parameter, run-raisetech-sample-config is true, the
  # job is triggered.
  sample-jobs:
    when: << pipeline.parameters.run-raisetech-sample-config >>
    jobs:
      - cfn-lint

